name: Build Wheels

on: [push, pull_request]

env:
  CIBW_BUILD_VERBOSITY: 2
  CIBW_ARCHS_LINUX: x86_64
  CIBW_ARCHS_WINDOWS: AMD64
  CIBW_ARCHS_MACOS: universal2

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
