name: Build Wheels

on:
  push:
    branches: [main]

env:
  CIBW_BUILD_VERBOSITY: 2
  CIBW_ARCHS_LINUX: x86_64
  CIBW_ARCHS_WINDOWS: AMD64
  CIBW_ARCHS_MACOS: universal2
  CIBW_BEFORE_BUILD_WINDOWS: "pip install delvewheel"
  CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair -w {dest_dir} {wheel}"
  CMAKE_BUILD_PARALLEL_LEVEL: 4


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [reticula-build-ubuntu-22.04, reticula-build-windows-2022]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.3

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
