name: documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.2
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Prerequisits
      run: pip install sphinx sphinxcontrib-bibtex


    - name: Build ⚙️
      working-directory: docs/
      run: make html

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.2
      with:
          branch: gh-pages
          folder: docs/_build/html
          clean: false
