name: documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2.4.2
    - uses: actions/setup-python@v3
      with:
        python-version: '3.11'  # sphinxcontrib-bibtex is not compatible with 3.12 https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/345
        architecture: 'x64'

    - name: Prerequisits
      run: pip install sphinx sphinxcontrib-bibtex furo sphinx-copybutton
        sphinx_design sphinxext-opengraph sphinx-sitemap toml


    - name: Build ⚙️
      working-directory: docs/
      run: make html

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.2
      with:
          branch: gh-pages
          folder: docs/_build/html
          clean: false
