name: Run tests
on: [workflow_dispatch]

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  SKBUILD_CMAKE_ARGS: "-DCMAKE_C_COMPILER_LAUNCHER=ccache;-DCMAKE_CXX_COMPILER_LAUNCHER=ccache"
  CCACHE_NOHASHDIR: "true"
  CCACHE_COMPILERCHECK: "content"

jobs:
  run_tests:
    name: Running tests
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
          cache: 'pip'

      - name: Update pip
        run: python -m pip install -U pip

      - name: install pip-compile
        run: python -m pip install pip-tools

      - name: compile dependency list
        run: pip-compile --all-build-deps --all-extras --strip-extras pyproject.toml -o comp-req.txt

      - name: install build deps
        run: python -m pip install -r comp-req.txt

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          verbose: 2
          max-size: 5GB

      - name: Build and install reticula
        run: python -m pip install .[test] -v

      - name: Run tests
        run: python -m pytest .
